<?php echo $this->doctype(); ?>
<html>
    <head>
        <meta charset="utf-8">

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php 
            echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                    ->prependStylesheet($this->basePath() . '/css/jquery.mobile.css');
            echo $this->headScript()->prependFile("https://js.stripe.com/v2/");
            echo $this->headScript()->prependFile($this->basePath() . '/js/jquery-1.11.1.js');
            echo $this->headScript()->prependFile($this->basePath() . '/js/jquery.mobile.js');
        ?>
        
    <style>

        .input-error {
            border: 1px solid red !important;
        }

        .ui-content {
            padding:4px;
        }

        #expiration-container .ui-btn {
            font-size:12px;
        }

        #expiration-container .ui-select .ui-btn-icon-right .ui-icon {
            right: 7px;
        }

        .ui-field-contain {
            border-bottom-style:none;
        }

        .ui-field-contain, .ui-mobile fieldset.ui-field-contain {
            padding: 0.6em 0;
        }

        #expirarion-month-button span {
            min-width: 100px !important;
        }
        #expirarion-year-button span {
            min-width: 90px !important;
        }

        .ui-btn-icon-right {
            padding-right: 2.3em;
        }

    </style>

    </head>
    <body>
        <?php echo $this->content; ?>
    </body>
</html>
