<?php echo $this->doctype(); ?>
<html>
    <head>
        <meta charset="utf-8">

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php 
            echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                    ->prependStylesheet($this->basePath() . '/css/jquery.mobile.css');
            echo $this->headScript()->prependFile($this->basePath() . '/js/jquery-1.11.1.js');
            echo $this->headScript()->prependFile($this->basePath() . '/js/jquery.mobile.js');
        ?>

    </head>
    <body>
        <?php echo $this->content; ?>
    </body>
</html>
