<div data-role="page" id="page1">
    <div role="main" class="ui-content">
        <div data-role="tabs" id="tabs">
            <div data-role="navbar">
                <ul>
                    <li><a href="/api/payment/add-card">Add card</a></li>
                    <li><a href="/api/payment/pay-with-existing">Pay with existing card</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>